package reports

const userFacingErrorMessage = "an unexpected error occurred, please try again later"
